### PR TITLE
feat: deprecate autocomplete appropriate check

### PR DESCRIPTION
**Pull request by clottman**
Deprecates autocomplete-appropriate

Closes issue: #2912

### CODE REVIEW

**Review by straker — CHANGES_REQUESTED** [review]
I talked to Wilco and he mentioned that we should also remove the check from the rule metadata as well. Sorry about that.

**Comment by clottman** [comment]
@straker I'm not sure what you mean by that, would you mind being more specific? 

I did notice looking at some other deprecated checks that the impact for the others was 'minor' - it makes sense to me that a deprecated check shouldn't be a severe impact, so I made that change. Can reverse it if that was the wrong call.

**Comment by clottman** [comment]
Ah I think I figured it out! :D

**Comment by straker** [comment]
Sorry missed the first question. Yes you removed it correctly. As for the impact change I don't think we should do that as the impact is based on user testing. The tests will also need to be updated with the removal of the check as those failures will no longer fail.

**Review by WilcoFiers — APPROVED** [review]

**Comment by WilcoFiers** [comment]
Reviewed for security.

**Pull request merged**
