### PR TITLE
docs: add all reporters to axe.configure parameters

### PR DESCRIPTION
**Pull request by straker**
Closes issue: #1560

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [x] Follows the commit message policy, appropriate for next version
- [x] Has documentation updated, a DU ticket, or requires no documentation change
- [x] Includes new tests, or was unnecessary
- [x] Code is reviewed for security by: Stephen

### CODE REVIEW

**Comment by adilsofficial** [comment]
I'm trying to generate the JSON-LD encoded EARL format result. Is there <code>axe.configure({reporter: "?"})</code> parameter to generate EARL results?

**Comment by stephenmathieson** [comment]
Hey @adilsofficial! There is an EARL reporter. It's provided as a [separate package](https://github.com/dequelabs/axe-reporter-earl). To use it, you'll have to:

```
npm install --save axe-reporter-earl
```

Then in your code, do:

```js
import earlReporter from 'axe-reporter-earl'

axe.configure({ reporter: earlReporter })
```

**Comment by adilsofficial** [comment]
Hi Stephen,
Thank you so much for replying, I tried it but recieving the same results. I would like to tell you that I'm using axe-webdriverjs to analyze and print the results. Do you want me to share the code with you?
Thanks

**Comment by WilcoFiers** [comment]
@adilsofficial I left you a comment here: https://github.com/dequelabs/axe-reporter-earl/issues/8 I would also be interested to learn what you are using this for. Drop me a message somewhere if you could.

**Pull request merged**
