### PR TITLE
Add missing elements that have a factor on contrast

### PR DESCRIPTION
**Pull request by mfairchild365**
`document.elementsFromPoint` does not include the `TBODY` and `THEAD` elements, so contrast was not being calculated correctly under some circumstances involving those elements. See added tests for examples.

### CODE REVIEW

**Comment by dylanb** [comment]
@mfairchild365 the changes are good but I just noticed that the commit messages do not match our required style (which allows us to generate our release notes). Could you fix this using rebase?

**Comment by mfairchild365** [comment]
@dylanb rebase was giving me grief, so I just deleted the branch, added the changes back, and made a new commit.

**Comment by dylanb** [comment]
Awesome!! @WilcoFiers @marcysutton any further comments?

**Comment by marcysutton** [comment]
Thanks so much for the contribution @mfairchild365! I ran the tests on this branch since Circle still isn't running on forks (#497) and they look all good. 

It seems like a good addition to me; I wish we didn't have to do so much to shim support for `document.elementsFromPoint` but I'm glad we already had logic in place to expand upon. I didn't even know you could style those elements, TIL! :)

**Comment by marcysutton** [comment]
I'll make a few changes so this can go into `develop-2x` as well.

**Pull request merged**
