### PR TITLE
ci: use correct environment variable

### PR DESCRIPTION
**Pull request by michael-siek**
Ref: https://github.com/srggrs/assign-one-project-github-action/issues/65

### CODE REVIEW

**Review by stephenmathieson — CHANGES_REQUESTED** [review]
Why?

**Comment by stephenmathieson** [comment]
See https://github.com/dequelabs/axe-core/runs/7757770044?check_suite_focus=true. It appears the issue is not the lack of quotes, but something with `jq` instead:

image

**Comment by straker** [comment]
Cause the action is currently failing and we don't know why other than looking at the docs they use single quotes for the url so we're trying that to see if it works https://github.com/dequelabs/axe-core/runs/7757770044?check_suite_focus=true

**Comment by stephenmathieson** [comment]
Wrapping a string in quotes is redundant in YAML. Look at the logs from that action:

image


Note that the URL _is_ wrapped in quotes.

**Comment by straker** [comment]
We found the issue https://github.com/srggrs/assign-one-project-github-action/issues/82. Looks like we need to switch to a different action

**Pull request closed without merging**
