### PR TITLE
Get develop-2x up to date with support docs (with commit history)

### LINKED ISSUE #616: Expose lookupTables through public API
As part of our ongoing Support agreement, we had a request to expose the ARIA lookupTables through the public axe-core API. These are pretty stable, so I don't anticipate much work in the way of maintaining backwards compatibility.

I believe the goal is to expose the roles, attributes, and global attributes inside of rules and checks.

https://github.com/dequelabs/axe-core/blob/develop/lib/commons/aria/index.js

### LINKED ISSUE #617: Expose select commons/utils functions via public API
As part of our ongoing Support agreement, we need to expose select commons and util functions through the public API. For now we just need a few to start, but we may determine it makes more sense to expose an entire set at once.

- [aria.implicitRole](https://github.com/dequelabs/axe-core/blob/develop-2x/lib/commons/aria/roles.js#L105)
- [aria.label](https://github.com/dequelabs/axe-core/blob/develop-2x/lib/commons/aria/label.js)
- [dom.isVisible](https://github.com/dequelabs/axe-core/blob/develop-2x/lib/commons/dom/is-visible.js#L28)

### PR DESCRIPTION
**Pull request by marcysutton**
I redid this merge by cherry-picking commits so they would be included in the commit history, instead of a new commit from merging the jsdoc branch. It should be more helpful for our changelog as compared to the other one.. Hopefully I didn't miss anything.

@WilcoFiers to answer your question from the previous PR, we can cherry-pick the lookupTable commit into 3x.

Closes #616
Closes #617

### CODE REVIEW

**Comment by iamrafan** [comment]
@marcysutton hey, I think #559 is still missing, can you please add it

**Comment by marcysutton** [comment]
Hi @iamrafan! I assumed that was covered by https://github.com/dequelabs/axe-core/commit/86b4a0e3b1e6951221723698a722dfbfd31e1eff. It looked like the work had already been done in the 2x branch. @isner, can you confirm?

**Comment by iamrafan** [comment]
@marcysutton Yes, my bad. It has already been added to 2x branch. I missed out as I could not find it in the release notes and the commit message being different here.

**Comment by marcysutton** [comment]
It is in the changelog for 2.5.0, but the commit message could be a bit more descriptive with "Closes #559".

**Comment by iamrafan** [comment]
Sure, thanks.

**Pull request merged**
