### PR TITLE
feat(i18n): add Danish (da-DK) translation

### PR DESCRIPTION
**Pull request by ddfreiling**
Adds Danish localization of Ace.

Thanks for your great work from Nota in Denmark.

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**

- [ ] Follows the commit message policy, appropriate for next version
- [ ] Code is reviewed for security

### CODE REVIEW

**Comment by straker** [comment]
Thanks for the pr! We'll see if we can find anyone who speaks Danish to look it over.

**Comment by WilcoFiers** [comment]
@ddfreiling have you had a chance to process the feedback you received from Marianne yet?

**Comment by ddfreiling** [comment]
@WilcoFiers I'll be able to do it this weekend or monday.

**Comment by WilcoFiers** [comment]
@ddfreiling any luck? No rush though, just wondering if there's something I could help out with.

**Comment by ddfreiling** [comment]
> @ddfreiling any luck? No rush though, just wondering if there's something I could help out with.

Been very busy at work, will try and look at it tonight.

**Comment by ddfreiling** [comment]
@WilcoFiers Translation has finally been reviewed and improved based on review by Marianne

**Pull request merged**
