### PR TITLE
types: add `element` to NodeResults

### PR DESCRIPTION
**Pull request by koddsson**
Add the `element` property to `NodeResult` interface.

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**

- [ ] Follows the commit message policy, appropriate for next version
- [ ] Code is reviewed for security

### CODE REVIEW

**Comment by straker** [comment]
Thanks for the pr. Where were you seeing the `element` property of `NodeResult`? I'm not seeing it myself.

image

**Comment by koddsson** [comment]
Screenshot 2020-05-06 at 09 26 52

I think you need to pass `elementRef: true` into the [options parameter](https://www.deque.com/axe/axe-for-web/documentation/api-documentation/#options-parameter).

**Comment by straker** [comment]
Ah, that makes more sense. Thanks.

**Comment by koddsson** [comment]
Hey @straker 👋🏻 

I just noticed that v3.5.4 has been released but it doesn't include this change. At which point do commits in the `develop` branch end up in a release?

**Comment by koddsson** [comment]
> Sorry about that. We've been working on a 4.0 release and just needed to get a bug fix out for color-contrast a bit earlier. This will be in the 4.0 release.

Ah no worries! I was just curious as when the change would land. Thanks for the explanation.

**Comment by dylanb** [comment]
@straker don't forget to check the security review checkbox - change is obviously ok but...

**Pull request merged**
