### PR TITLE
fix: ignore stylesheets fetching when is a inline style

### PR DESCRIPTION
**Pull request by EduSantosBrito**
Closes: #4137

This fixes the issue when there's a inline style tag inside the shadowRoot. Since the inline style doesn't have a href, there's no need to fetch it. This is usual on Lit components.

### CODE REVIEW

**Comment by WilcoFiers** [comment]
@EduSantosBrito Quick ping, have you had a chance to look at Steve's comment?

**Comment by EduSantosBrito** [comment]
Hey! I have time this week to look at it. I was on holiday last week hahaha

**Comment by EduSantosBrito** [comment]
Ok, after debugging for some hours I found that document.implementation.createHTMLDocument breaks HTMLStyleElement.sheet. There's some issues opened related to that https://github.com/jsdom/jsdom/issues/3179

This makes sense why the browser using `selenium-webdriver` was working and the test using `jsdom` wasn't.

Quick ping @WilcoFiers @straker

**Comment by straker** [comment]
@EduSantosBrito Thanks for that investigation. That helps understand why `style` tags don't have a `.sheet` property, but I'd still like to know how the `style` tag gets through the filter method. `filerStyleAndLinkAttributesInDocumentFragment` [looks for any node with `nodeName` of `style`](https://github.com/dequelabs/axe-core/blob/develop/lib/core/utils/preload-cssom.js#L215-L216) and should remove it from the list before passing to the function that checks for `.sheet`. Somehow that's not happening in your case when it should be.

**Comment by straker** [comment]
That makes sense. Thanks for the looking into that for us.

**Review by straker — CHANGES_REQUESTED** [review]
Just updating the comment to reflect the investigations on when and why this is needed.

**Review by straker — APPROVED** [review]

**Comment by straker** [comment]
Approved for security.

**Pull request merged**
