### PR TITLE
fix(messages): Change messages from "page" to "document" where appropriate

### PR DESCRIPTION
**Pull request by iamrafan**
A minor fix that was missed in #983 

Closes issue: #983

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [x] Follows the commit message policy, appropriate for next version
- [x] Has documentation updated, a DU ticket, or requires no documentation change
- [x] Includes new tests, or was unnecessary
- [x] Code is reviewed for security by: @WilcoFiers

### CODE REVIEW

**Comment by WilcoFiers** [comment]
Thanks Guru. The spacing seems to be off though. Can you sort that?

**Comment by iamrafan** [comment]
@WilcoFiers looks like I had the correct indentation of tabs with size 2

**Comment by WilcoFiers** [comment]
Thinking about this a little more... I think the current description is probably better. I get where you're coming from, but according to ARIA, if you put in multiple `role=document` elements on the page, each of them is allowed a main role. I don't think the check currently implementation allows that, but it probably should. Thoughts?

**Comment by iamrafan** [comment]
@WilcoFiers Yes, I too feel it should allow each of the child ```iframes``` or ```role=document``` to have its own main landmark and the wording "Document" seems more appropriate than "Page".
Do you want me to change it to "Page" in all the rules/checks that we changed in https://github.com/dequelabs/axe-core/issues/983#issuecomment-404273984, #1003 ?

**Comment by WilcoFiers** [comment]
@iamrafan sounds like a plan :-)

**Comment by iamrafan** [comment]
@WilcoFiers Done, please review.

**Comment by dylanb** [comment]
@WilcoFiers Why did this PR not run the checks before it was merged?

**Comment by WilcoFiers** [comment]
@dylanb It did. All the checks passed. Axe is randomly failing for some reason. I saw it fail on this PR too, reran the build and it passed. There's nothing in this PR that looked like it could have caused it, so I figured the culprit was already in develop.

**Pull request merged**
