### PR TITLE
Release 4.1.2

### PR DESCRIPTION
**Pull request by straker**

### CODE REVIEW

**Comment by straker** [comment]
Please don't merge this just yet. We had a request to talk about it tomorrow.

**Comment by stephenmathieson** [comment]
Do we now need to [update the tests](https://github.com/dequelabs/axe-core/pull/2792/commits/47085c6cea3d8999a984cb687b498512cc785896) for every release?

**Review by WilcoFiers — APPROVED** [review]
## Release Audit
- [x] https://github.com/dequelabs/axe-core/pull/2789
- [x] https://github.com/dequelabs/axe-core/pull/2790

**Review by WilcoFiers — APPROVED** [review]

**Comment by keith-rhodes-0723** [comment]
Reviewed.

**Pull request merged**
