### PR TITLE
Fix audio-caption SC tag

### LINKED ISSUE #686: audio elements must have a track for captions - does this rule apply to prerecorded audio-only media
Does the rule "audio elements must have a track for captions" apply to prerecorded audio-only content: (https://dequeuniversity.com/rules/axe/2.6/audio-caption)? 

If yes: this is not a WCAG requirement. Per SC 1.2.1, audio-only content is required to have an "alternative for time-based media" where "alternative for time-based media" is a "document including correctly sequenced text descriptions of time-based visual and auditory information and providing a means for achieving the outcomes of any time-based interaction". So a transcript satisfies SC 1.2.1. SC 1.2.2 (referenced in https://dequeuniversity.com/rules/axe/2.6/audio-caption) is not applicable to prerecorded audio-only.

### PR DESCRIPTION
**Pull request by WilcoFiers**
Closes #686

### CODE REVIEW

**Comment by chaals** [comment]
Don't the tests **also** apply to 1.2.2, 1.2.4, and 1.2.9?

(I am not sure if I misunderstood the tag system though)

**Comment by WilcoFiers** [comment]
@chaals I don't think it does. Those are video SCs, this is audio only.

**Comment by chaals** [comment]
But they require, for video which includes audio (or for live-streamed audio in the case of 1.2.9 I think), audio captions - i.e. the same requirement.

(if they do apply, am I making the right assumption that multiple checkpoint tags should be applied?)

**Comment by WilcoFiers** [comment]
The audio-caption rule only checks `<audio>` elements. I don't see how 1.2.2 says:

> all prerecorded audio content in **synchronized media**

There's a slight assumption we are making that the `<audio>` element isn't synchronised with something else on the page, but I think that's generally not the case. So 99% of the time I would say this only applies to 1.2.1. Also as a rule of thumb, we use one SC, not all that may be applicable.

**Pull request merged**
