### PR TITLE
Align impact levels with Deque Way

### PR DESCRIPTION
**Pull request by WilcoFiers**
Thanks to the work of Matt Isner, I had a nice list to work from. I’ve double checked that for each impact I changed, it only changes the impact level of the rules I wanted to change. The changes are as follow:

| Rule			| Impact from		| Impact to
|-----------------------|-----------------------|---------------
| accesskeys		| critical		| serious
| blink			| minor			| serious
| marquee		| minor			| serious
| document-title	| moderate		| serious
| duplicate-id		| critical		| moderate
| heading-order		| minor			| moderate
| link-in-text-b	| critical		| serious
| listitem		| critical		| serious
| p-as-heading		| critical		| serious
| scope-attr-val	| critical, serious	| critical, moderate
| server-side-ima	| minor			| critical
| skip-link		| critical		| moderate
| table-duplicate-name	| moderate		| minor
| table-fake-caption	| critical		| serious
| th-has-data-cells	| critical		| serious
| video-description	| serious		| critical
| bypass		| critical		| serious
| empty-heading		| moderate		| minor
| frame-title		| critical		| serious
| link-name		| critical		| serious
| object-alt		| critical		| serious

### CODE REVIEW

**Comment by WilcoFiers** [comment]
We might want to hold off on releasing this until aXe 3.0, as it might be a impactful change for some users.

**Comment by marcysutton** [comment]
How did you double-check the impact for rules vs. checks (that are potentially reused in multiple rules)? I'm wondering if we should write any tests around that to make it less of a manual process.

**Comment by WilcoFiers** [comment]
@marcysutton frustratingly enough, just a regular file search, look at all the rules that have that particular check, then look at the other checks they have and make sure one of those has the impact level we want. With 'any', it'll always take the highest impact level, so just one of them has to have 'critical' for example. for the rule to turn out with critical.

**Comment by dylanb** [comment]
color-contrast went from serious to serious?

I don't see a huge reason to delay this release...perhaps users could comment here if they think it will be disruptive

**Comment by WilcoFiers** [comment]
The color-contrast hasn't changed. That one had been updated a few weeks back. I think we can merge this.

**Pull request merged**
