### PR TITLE
feat(l10n): French localization

### PR DESCRIPTION
**Pull request by ffoodd**
Hi there!

Since I'm using aXe on a daily basis — thanks for this amazing tool! —, I wanted to contribute by translating it in French.
I did my best to follow your contribution guidelines, hoping I passed!

Credits to a few friends who helped me:

- @dzc34
- @PhilippeVay
- @audrasjb

### CODE REVIEW

**Comment by WilcoFiers** [comment]
Thank you very much!! That is fantastic!

**Comment by ffoodd** [comment]
You're welcome!

FWIW, I did my best to use the RGAA glossary, but it's not that easy :) I asked a few people as reviewers, please let them a few days for proofreading ;)

**Comment by dylanb** [comment]
@audrasjb could you please sign the contributor license agreement - we cannot merge any of the changes until this is signed by all contributors

**Comment by audrasjb** [comment]
Hi @dylanb 

I just signed the CLA. Let me know if something went wrong.
Cheers,
Jb

**Comment by dylanb** [comment]
@ffoodd and @dboudreau - is this PR ready for merging?

**Comment by ffoodd** [comment]
I think so, I don't get any issue nor PR since a few days 😊

**Pull request merged**
