### PR TITLE
chore(release): 4.3.1

### PR DESCRIPTION
**Pull request by straker**

### CODE REVIEW

**Comment by stephenmathieson** [comment]
Shouldn't [this](https://github.com/dequelabs/axe-core/pull/3075) land first?

**Review by WilcoFiers — APPROVED** [review]
## Release Audit
- [x] https://github.com/dequelabs/axe-core/pull/3079

**Comment by straker** [comment]
Maybe? I'm not sure it really matters in this case.

**Comment by dylanb** [comment]
reviewed

**Pull request merged**
