### PR TITLE
fix(is-valid-autocomplete): allow autocomplete="one-time-code" 

### PR DESCRIPTION
**Pull request by lencioni**
This autocomplete value can be used by some browsers to automatically
fill in the value after receiving a one-time-code for 2-factor
authentication. More info:

- https://github.com/whatwg/html/pull/4573
- https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element
- https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#Values
- https://www.twilio.com/blog/html-attributes-two-factor-authentication-autocomplete

Closes issue: #2335

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**

- [x] Follows the commit message policy, appropriate for next version
- [x] Code is reviewed for security

### CODE REVIEW

**Comment by straker** [comment]
Just need to sign the license/cla and we get this merged in.

**Comment by faroelrozi** [comment]
Dikirim dari Outlook Seluler
________________________________

**Comment by lencioni** [comment]
@straker CLA signed, thanks!

**Comment by backwardok** [comment]
@straker Did this get added to a release yet? I looked at 4.0.1 and 4.0.2, which have both released since this PR was merged, from the [changelog](https://github.com/dequelabs/axe-core/blob/develop/CHANGELOG.md), but I didn't see this change.

**Comment by straker** [comment]
@backwardok Yep, should have made it into the [4.0.0](https://github.com/dequelabs/axe-core/releases/tag/v4.0.0) release.

**Comment by backwardok** [comment]
Great, thank you!

**Pull request merged**
