### PR TITLE
fix(metadata): consistent use of 'must' and 'should'

### PR DESCRIPTION
**Pull request by WilcoFiers**
Ensure that best practices never use the word "must" in its description / help text, and that other rules don't use the word "should".

Closes issue: #1491

### CODE REVIEW

**Comment by stephenmathieson** [comment]
Is this a "feature"? Seems like a `docs` or `fix` commit to me. 🤔

**Comment by WilcoFiers** [comment]
@stephenmathieson Wouldn't say its docs... but yeah maybe it's more of a fix.

**Review by stephenmathieson — COMMENTED** [review]
Change LGTM, but @straker should probably take a look since this touches `lib/rules`.

**Comment by dylanb** [comment]
@WilcoFiers this change does not seem right to me. Saying `aria treeitem items should have an accessible name` is not as accurate as saying `aria treeitem items must have an accessible name`

Under what circumstances are these items allowed to not have an accessible name?

**Comment by WilcoFiers** [comment]
@dylanb Yeah that one isn't too obvious. I ran this one by JC before we put it in. If a treeitem is interactive, it would need a name, but if it isn't, it's harder to argue that it does. ARIA says it does, which is why we put it as a best practice. But if you have a static treeitem, it's basically no different than a nested list. We don't require listitems to have an accessible name - ARIA doesn't either.

So that's why we landed on that one. I suppose we could've made it a WCAG rule and restrict it to focusable elements, but then again, we don't fail focusable listitems if they're empty either. This seemed like the most appropriate way to do it. It's maybe not as strict as it could we if we further refined it, but it also gets not false positives.

**Comment by dylanb** [comment]
I am worried about all of them - that one was just an example.

I am concerned that these changes are not being made with usability in mind. We need to remember that 97%+ of the people reading these do not know the nuances that the JC would be concerned about.

I want to put the brakes on this and have a usability discussion about these first and foremost before we make any changes.

**Comment by dylanb** [comment]
Discussed with @WilcoFiers : we are good to go on this

**Review by dylanb — APPROVED** [review]

**Pull request merged**
