### PR TITLE
docs: Fix broken link to heading-order-evaluate.js

### PR DESCRIPTION
**Pull request by dsanz**
Just found a dangling link, not sure if this required to create an issue on its own
Best

### CODE REVIEW

**Comment by straker** [comment]
Nice catch. Just need you to sign the CLA and we can get this merged in.

**Comment by straker** [comment]
@dsanz have you had a chance to sign the CLA (sometimes it doesn't process properly)?

**Comment by WilcoFiers** [comment]
OK, given how minor the fix is, I'm going to merge this without the CLA signed. Not much to copyright about fixing a broken link.

**Review by WilcoFiers — APPROVED** [review]

**Comment by WilcoFiers** [comment]
Reviewed for security.

**Pull request merged**
