### PR TITLE
chore(i18n): Update pt_BR.json

### PR DESCRIPTION
**Pull request by thiagoeec**
Translate new strings

### CODE REVIEW

**Comment by straker** [comment]
Thanks for the updated translation. We'll get this in as soon as we can, but still might take a bit as we're busy preparing for the 4.2 release coming up. We'll at least try to get it in for the release though.

**Review by carlosapaduarte — CHANGES_REQUESTED** [review]

**Comment by dylanb** [comment]
@thiagoeec please check the changes suggested by @carlosapaduarte and if in agreement, we will merge

**Comment by thiagoeec** [comment]
> @thiagoeec please check the changes suggested by @carlosapaduarte and if in agreement, we will merge

Thanks @carlosapaduarte for reviewing it and catching many typos.
It's all good, @dylanb. It can be merged. Thanks!

**Review by dylanb — APPROVED** [review]
based on the Portuguese speakers' comments

**Comment by dylanb** [comment]
Security review done - security review application not working

**Comment by dylanb** [comment]
@straker @WilcoFiers another example of failing security review app

**Pull request merged**
