### PR TITLE
fix(check): fix bug with async checks

### PR DESCRIPTION
**Pull request by justinhorvitz**
The correct field to set on CheckResult is 'result' not 'value'

### CODE REVIEW

**Comment by marcysutton** [comment]
Was this not working before? A related issue would help.

**Comment by WilcoFiers** [comment]
I don't think it was. I had tried to write the frames-untested rule and got stuck on the async stuff too. I never had a chance to look into it. But I'll have a look when checking this PR. Thanks for contributing @justinhorvitz.

**Comment by justinhorvitz** [comment]
Since checkResult.result is undefined, all async checks will currently be considered incomplete.

**Comment by dylanb** [comment]
@justinhorvitz This problem underscores a gap in our integration tests - can you add an integration test as part of this change?

**Comment by justinhorvitz** [comment]
Unfortunately I don't believe I'll have the time to figure out how to add an integration test.

**Comment by WilcoFiers** [comment]
I'm happy to work on that @justinhorvitz. Thanks for the contribution.

**Comment by dylanb** [comment]
@WilcoFiers Do you know why the Circle tests are failing on this PR? I pulled the PR down onto my local machine and ran all tests and they passed.

**Comment by WilcoFiers** [comment]
@dylanb No clue, I a rerun fixed it though. We do get the occasional PhantomJS timeout. Nothing to worry about I think.

**Comment by WilcoFiers** [comment]
Closing the PR and continue the work in #630.

**Pull request closed without merging**
