### PR TITLE
build: add AppVeyor config

### PR DESCRIPTION
**Pull request by nschonni**
Adds testing for Windows related to #519
Currently failing here for the last set of IE tests https://ci.appveyor.com/project/nschonni/axe-core/build/1.0.1

### CODE REVIEW

**Comment by WilcoFiers** [comment]
This is really excellent! Thanks a whole bunch! We'll have to fix the IE issues though before we can merge this in.

**Comment by marcysutton** [comment]
We'd have to run Babel on our tests to fix some of those issues, like `map` not being defined.

**Comment by nschonni** [comment]
OK, not sure if I've really figured this out, but I think the issue might be that `pollyfillElementsFromPoint` appears to return a NodeList instead of an Array. This appears to be the issue with the color-contrast failures.

**Comment by WilcoFiers** [comment]
I'm happy to take a crack at it as soon as things ease up.

**Comment by WilcoFiers** [comment]
Started looking at some of these issues yesterday. I'm a little surprised at some of these. It was a while since I last ran everything though IE, but some of these issues seem a lot older than that. Not sure how they escaped.

Anyway, I'm merging this one in. There are a bunch of separate issues. We'll be fixing them, and as soon as that's done we'll enable Appveyor on all PRs from then on.

**Comment by WilcoFiers** [comment]
@nschonni I'm trying to get this working. We've fixed some of the IE errors, but I can't get the tests to pass. Phantom keeps timing out. Did you set anything up that's not in this config to get this working? https://ci.appveyor.com/project/WilcoFiers/axe-core

**Pull request merged**
