### PR TITLE
fix: Avoid require conflict with Cypress [#1405]

### LINKED ISSUE #1405: [3.2.0] Cannot find module './lib/axios'
Attempts to update `axe-core` from 3.1.2 to 3.2.0 are causing Cypress tests to fail. From the error message, it looks like it can't resolve `axios` anymore? 

Expectation: no errors

Actual: `Error: Cannot find module './lib/axios' from '/root/project/node_modules/axe-core'`

Motivation: N/A

<pre><code>
axe-core version: 3.2.0
axe-webdriver, extension or other integration version: N/A

Browser and Assistive Technology versions

For Tooling issues:
- Node version: 10  
- Platform: all 
</code></pre>

Here's a reproduction using `create-react-app` and Cypress (test copied from #755):

https://github.com/wKovacs64/cypress-axe-core-320

(Run `yarn cy:run` to start Cypress in headless mode in your CLI or `yarn cy:open` to launch the GUI.)

Thanks.

### PR DESCRIPTION
**Pull request by WilcoFiers**
Use derequire the rename all uses of `require` to `_dereq_` to avoid the problem of Cypress overloading the `require` method.

Closes #1405

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [x] Follows the commit message policy, appropriate for next version
- [x] Has documentation updated, a DU ticket, or requires no documentation change
- [x] Includes new tests, or was unnecessary
- [x] Code is reviewed for security by: Stephen

### CODE REVIEW

**Comment by stephenmathieson** [comment]
This seems scary. I'd like to hear more about why this is necessary before OK'ing the code.

**Comment by WilcoFiers** [comment]
@stephenmathieson Cypress seems to be replacing any variable with the name `require` with its own require method. I didn't dig into exactly why that is. I searched, but couldn't find any documentation about this. Renaming all uses of `require` to `_dereq_` gets around that problem.

What is your concern with doing this? I realise that if derequire messes up, this could go wrong, but the same is true for browserify. That's why I used derequire, it's made to do this.

**Comment by stephenmathieson** [comment]
> Cypress seems to be replacing any variable with the name require with its own require method. I didn't dig into exactly why that is. I searched, but couldn't find any documentation about this.

Wow, OK. That's very strange. I wonder why that is 🤔 

> What is your concern with doing this?

I'm just worried about adding _another_ layer of transformation to the codebase, especially since in this PR we're transforming code that we don't own/maintain (`dot`, `axios`, and `es-promise`). It's generally recommended that you **do not** run Babel/etc over your `node_modules`, so I'm of the same mindset with the "derequire" transformation.

However, since this is urgent, and the tests are all green, let's give this a go 😄

**Comment by stephenmathieson** [comment]
> However, since this is urgent, and the tests are all green, let's give this a go 😄

I was wrong. Tests are now failing.

**Comment by stephenmathieson** [comment]
Based on #1427, it seems like using axe-core in Cypress still isn't working as expected.

**Comment by artemkochnev** [comment]
@stephenmathieson I just want to add that the issue I'm seeing only exists when using webpack to preprocess files. If I let Cypress manage things itself, using axe-core works without issue.

**Comment by YOU54F** [comment]
This is an issue with webpack, I have switched to 

https://github.com/cypress-io/cypress-browserify-preprocessor

which has resolved the issue

**Pull request merged**
