### PR TITLE
fix(commons/dom): change isFocusable to check visibility in screenreader mode

### LINKED ISSUE #647: Bug: dom.isFocusable mistakenly concludes that invisible elements are unfocusable
[dom.isFocusable](https://github.com/dequelabs/axe-core/blob/develop/lib/commons/dom/is-focusable.js#L17) will return false for any element that isn't visible, including elements that are clipped or simply positioned off screen. In reality, those elements are focusable. Demo: https://codepen.io/0ddfell0w/pen/KZpZVZ

### PR DESCRIPTION
**Pull request by 0ddfell0w**
Lets isFocusable tell the difference between elements that are still focusable despite being invisible

fixes #647

### CODE REVIEW

**Comment by 0ddfell0w** [comment]
@dylanb done

**Comment by dylanb** [comment]
Leaving for @WilcoFiers to determine when to merge

**Comment by 0ddfell0w** [comment]
@dylanb i actually think this might not work, isFocusable() will return True for the **unfocusable** `<button style="visibility:hidden" tabindex="0">Hidden button forced into the tab order</button>`

isFocusable will have the following logic:
is it natively focusable? No, because it's hidden
is it a button: Yes, therefor it's focusable.

**Comment by 0ddfell0w** [comment]
I'll add tests to isFocusable for the disabled/screenreader-invisible cases as part of resolving this issue

**Comment by 0ddfell0w** [comment]
@dylanb @WilcoFiers didn't want to force push over approved changes, so here's another PR with the changes I think are correct: https://github.com/dequelabs/axe-core/pull/658

**Comment by WilcoFiers** [comment]
@0ddfell0w Does that mean we can close this? If so, please go ahead.

**Pull request closed without merging**
