### PR TITLE
fix: prevent crash on jsdom when preloading CSSOM

### LINKED ISSUE #3753: `getStylesheetsFromDocument` crash on JSDOM: `TypeError: Cannot read properties of undefined (reading 'mediaText')`
### Product

axe-core

### Product Version

4.5.0

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation

I'm using `axe-core` in `jsdom` environment when testing UIs with `jest-axe`. When updating `axe-core` from `4.4.3` to `4.5.0` a new error started to show up in logs.

#### Actual

The `getStylesheetsFromDocument` function crashes when `sheet.media.mediaText` is run. The `cssom` package used by `jsdom` does not implement [`StyleSheet.media`](https://developer.mozilla.org/en-US/docs/Web/API/StyleSheet/media), https://github.com/NV/CSSOM/issues/1. 

https://github.com/dequelabs/axe-core/blob/c1af750743d5c1ca369f55fd04dd0636edda612e/lib/core/utils/preload-cssom.js#L182-L193

#### How to Reproduce

Here is really minimal reproduction case with `getStylesheetsFromDocument` copied from `axe-core` to demonstrate the issue:

```js
const JSDOM = require("jsdom").JSDOM;

const dom = new JSDOM(`
    <!DOCTYPE html>
    <head>
        <style>
            @media (max-width: 1px) { a { color: red; } }
        </style>
    </head>
    <body>
        <p>Hello world</p>
    </body>
`);

function getStylesheetsFromDocument(rootNode) {
    return Array.from(rootNode.styleSheets).filter(function (sheet) {
        return filterMediaIsPrint(sheet.media.mediaText);
    });
}

function filterMediaIsPrint() {}

getStylesheetsFromDocument(dom.window.document);
// ^^ Uncaught TypeError: Cannot read properties of undefined (reading 'mediaText')
```

#### Additional context

`cssom` is unmaintained and the linked issue is 12 years old. I know adding such work-arounds in `axe-core`'s sources is not ideal, but as everything has been working nicely for many years, I hope this small fix could be applied.

### PR DESCRIPTION
**Pull request by AriPerkkio**
- cssom package does not implement StyleSheet.media

<< Describe the changes >>

Adds a simple `if` to check whether `StyleSheet` has `media`.

Closes #3753

### CODE REVIEW

**Review by stephenmathieson — APPROVED** [review]

**Comment by stephenmathieson** [comment]
The fix LGTM. I don't understand what's going on with CI though.

**Comment by straker** [comment]
Thanks for the pr. Could you try pushing an empty commit to see if that fixes the checks?

```
git commit -m "trigger build" --allow-empty
```

**Comment by AriPerkkio** [comment]
I used the `commit --amend` to get new commit for re-triggering the build instead of `--allow-empty` - now the PR approval resetted. 🙃 

@stephenmathieson could you re-approved so we'll see if CI is now stable?

**Comment by AriPerkkio** [comment]
The CI seems to remain stuck. Any ideas what's going on?
As resetting the commits did not fix the CI, should I just create a new PR?

**Comment by straker** [comment]
Unfortunately I don't know what's going on with Circle. I've looked around but it seems the only answer is to contact Circle support and see if they can fix it. Before I do that though, I'm going to try committing to your pr and see if that triggers the build.

**Comment by straker** [comment]
Well that seems to have worked.

**Review by straker — APPROVED** [review]

**Comment by straker** [comment]
Reviewed for security

**Pull request merged**
