### PR TITLE
feat(i18n): add Hebrew translation

### PR DESCRIPTION
**Pull request by nadavkav**
Translated by Or Bar-Josef from the Weizmann institute of science, Israel.

<< Describe the changes >>

Closes issue:

### CODE REVIEW

**Comment by straker** [comment]
Thanks for the new translation! We'll find someone to review the changes who can speak Hebrew, so it may take a bit to get a review.

**Comment by nadavkav** [comment]
Thank you @straker

**Comment by straker** [comment]
Update on this. Thanks for your patience. We found someone to do the review. I'll try to have a pr to your branch with the changes they suggested within the next few days.

**Comment by nadavkav** [comment]
Thank you

**Comment by straker** [comment]
@nadavkav Just letting you know I opened a pr on your fork with the suggestions from the translator. Let me know if you have any questions.

**Comment by nadavkav** [comment]
@straker , I can not find the reviewer's suggestions please send a link.
And I do not understand the flow, do I need to do something?

**Comment by straker** [comment]
The suggestions can be found here https://github.com/nadavkav/axe-core/pull/1/files. It's a pr to your fork of axe-core. The flow would be to look at the differences between your file and the suggestions from the pr and if you accept all the changes to merge the pr on your fork. That should automatically update this pr with those changes.

**Comment by straker** [comment]
@nadavkav thanks for accepting the changes. It looks like our build is failing because your fork is out of date. I'll make another pr to update it for you.

**Comment by straker** [comment]
Here's the pr https://github.com/nadavkav/axe-core/pull/3

**Review by straker — APPROVED** [review]
Awesome! Thanks again for your patience while we worked to find someone to help us.

**Comment by straker** [comment]
Reviewed for security

**Pull request merged**
