### PR TITLE
docs: add links to issue impact

### PR DESCRIPTION
**Pull request by ortonpaul**
Add links to the [Issues Impact](https://github.com/dequelabs/axe-core/blob/develop/doc/issue_impact.md) page at a few spots in the documentation in response to #3942. Let me know if there are other places you can think of that make sense 👍🏼

### CODE REVIEW

**Comment by straker** [comment]
Thanks for the pr. The `docs/rule-descriptions.md` file is a generated file and so your changes will not keep. Instead you'll need to update the file that generates it which is https://github.com/dequelabs/axe-core/blob/develop/build/configure.js. Specifically you'll need to [modify the `impact` variable](https://github.com/dequelabs/axe-core/blob/develop/build/configure.js#L369) to add the links to the specific impact levels.

However, that'll add a lot of duplicate links to the page, so we should discuss with @WilcoFiers how we want to handle that.

**Comment by ortonpaul** [comment]
Ahhh I see! Thanks for the heads up. Maybe a link in the [table header](https://github.com/dequelabs/axe-core/blob/0080a7255eb7f246bb7b6f53974a95b65983b83a/build/configure.js#L19C30-L19C36) then or a footnote somewhere?

**Review by WilcoFiers — CHANGES_REQUESTED** [review]
@ortonpaul Thank you for the contribution, but I think this is a little much. One link in the API.md file, and one link in the rule description file is probably enough. As Steve pointed out the rule description file is generated. To update it you'll have to change some code in build/configure.js. 

You may also want to consider putting a link into the readme somewhere. I'm open to suggestions on where.

**Comment by straker** [comment]
@ortonpaul are you still interested in doing this work or could I close the pr?

**Comment by straker** [comment]
Closing due to inactivity

**Pull request closed without merging**
