### PR TITLE
fix(respondable): avoid crashes if the data in `window.postMessage` is `null`

### PR DESCRIPTION
**Pull request by esanzgar**
axe-core crashes if another process sends a `window.postMessage` with
data equals to `null`.

In the previous version, because `null` has a type of `'object'`, it
crashed when trying to access the `channelId`.

This change detects first if the data is not `null`.

### CODE REVIEW

**Comment by straker** [comment]
Thanks for the pr. Could you add a test for this case in the respondable test? Probably [after the repeater test](https://github.com/dequelabs/axe-core/blob/develop/test/core/utils/respondable.js#L531)

**Review by straker — DISMISSED** [review]
Thanks for the pr. Could you add a test for this case in the respondable test? Probably [after the repeater test](https://github.com/dequelabs/axe-core/blob/develop/test/core/utils/respondable.js#L531)

**Comment by esanzgar** [comment]
I added the test. I am not very familiar with the internals with axe-core, so I am afraid you will need to take it from there.

**Review by WilcoFiers — APPROVED** [review]

**Comment by straker** [comment]
Reviewed for security

**Pull request merged**
