### PR TITLE
test: More div tests for only-dlitems

### PR DESCRIPTION
**Pull request by WilcoFiers**
Adding in a few more tests as requested in #1076 by @dylanb 

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [x] Follows the commit message policy, appropriate for next version
- [x] Has documentation updated, a DU ticket, or requires no documentation change
- [x] Includes new tests, or was unnecessary
- [x] Code is reviewed for security by: Jey

### CODE REVIEW

**Comment by dylanb** [comment]
@WilcoFiers what about a mix of dl/dt items and other items?

**Comment by jkodu** [comment]
@WilcoFiers - Assigned to you, needs addressing of tests as requested above.

**Comment by WilcoFiers** [comment]
@dylanb another test added. Please approve.

**Comment by dylanb** [comment]
@WilcoFiers branches need updating

**Pull request merged**
