### PR TITLE
chore: Avoid publishing unnecessary files to NPM

### PR DESCRIPTION
**Pull request by WilcoFiers**
Speaks for itself.

Closes issue: none

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [x] Follows the commit message policy, appropriate for next version
- [x] Has documentation updated, a DU ticket, or requires no documentation change
- [x] Includes new tests, or was unnecessary
- [x] Code is reviewed for security by: @jkodu

### CODE REVIEW

**Comment by WilcoFiers** [comment]
@stephenmathieson those files are only used for development. This is just removing clutter.

**Comment by stephenmathieson** [comment]
Right. I'd call it a "chore" then, since it doesn't fix a bug.

**Comment by WilcoFiers** [comment]
@stephenmathieson updated.

**Comment by scurker** [comment]
Just a thought: Would it be better to use a [whitelist](https://docs.npmjs.com/files/package.json#files) instead of a blacklist?

**Comment by stephenmathieson** [comment]
@scurker yes, probably, but the path of least resistance is just adding these few entries to the existing `.npmignore`.

**Pull request merged**
