### PR TITLE
tests: start server on integration test

### PR DESCRIPTION
**Pull request by straker**
Closes issue: #2658 

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**

- [x] Follows the commit message policy, appropriate for next version
- [x] Code is reviewed for security

### CODE REVIEW

**Review by stephenmathieson — APPROVED** [review]
Looks like we're intentionally adding a race condition, but I'm not sure how else to handle this. LGTM but we should keep an eye on this.

**Comment by straker** [comment]
Nope, this is still timing out after 47 tests... I have no idea what is going on but I don't know how else to do this in a single command so we don't have to start the server beforehand

**Comment by stephenmathieson** [comment]
If you like, we can pair on it next week. Should I set something up?

**Comment by straker** [comment]
IT WORKS! So this is the "best" way I've found to do this but it adds a lot of npm scripts. 

`start-server-and-test` does what we want, but it has a problem in that it can't pass command line arguments to the test command. That resulted in creating individual test scripts for each of the browsers. Unfortunately, it also [has a bug in Windows](https://github.com/bahmutov/start-server-and-test/issues/239) that doesn't allow it to work with npm commands, so I had to create yet another set of individual test scripts so we can run the script name instead of a command.

**Review by stephenmathieson — APPROVED** [review]

**Comment by stephenmathieson** [comment]
Well done! Glad you figured it out!

**Review by WilcoFiers — APPROVED** [review]

**Pull request merged**
