### PR TITLE
fix: banner comment in generated axe files

### PR DESCRIPTION
**Pull request by jkodu**
- This PR ensures, generation of banner comments on `axe.js` and `axe.min.js` files as a part of `grunt build` step.
- `grunt-contrib-uglify` > 2.x has some API changes which replaced `preserveComments` with `options.comments` which is now adapted here.

Closes issue:
- https://github.com/dequelabs/axe-core/issues/1108

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [ ] Follows the commit message policy, appropriate for next version
- [ ] Has documentation updated, a DU ticket, or requires no documentation change
- [ ] Includes new tests, or was unnecessary
- [ ] Code is reviewed for security by: << Name here >>

### CODE REVIEW

**Comment by dylanb** [comment]
@jkodu Any way we can add an integration test for this? Seems like this keeps happening and it would be good to catch it in the build pre-publish.

**Comment by stephenmathieson** [comment]
An integration test seems like overkill to me, but this should work:

```bash
#!/bin/bash

e="/*! aXe"
for file in axe.js axe.min.js; do
  src=$(cat $file)
  if [[ $src != $e* ]]; then
    echo "$file does not contain required comment" >&2 
    exit 1
  fi
done 
```

**Comment by jkodu** [comment]
@dylanb @stephenmathieson 

Sure thing, can be done, but I will tackle that one (writing tests) separately as I need to write some tests to ensure these files are generated in the first place, before verifying the contents for comments etc. 

This was the agreed solution we came up in the retrospective to have tests around generated files and their timestamps, to avoid the issue we had with releasing axe earlier this week without generated files. @WilcoFiers and I believe this needs to be across all the projects, so will get around to that later.

**Comment by WilcoFiers** [comment]
@jkodu In thinking some more about build processes. I don't think we need prepublish tests for all projects, just the ones with complicated build steps. For some it might just be enough to check that the `dist` directory is there. Either way, please create a ticket to add a prepublish test to axe-core.

**Comment by jkodu** [comment]
Issue created to ensure build generated files exist - https://github.com/dequelabs/axe-core/issues/1117

**Pull request merged**
