### PR TITLE
fix: attempt to fix ci build failures.

### PR DESCRIPTION
**Pull request by jkodu**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message(s) follow our guidelines: https://github.com/dequelabs/axe-core/blob/develop/doc/code-submission-guidelines.md#git-commits
- [x] Changes to rules and checks appropriately support [Shadow DOM](https://github.com/dequelabs/axe-core/blob/develop/doc/developer-guide.md)
- [x] Changes have been tested in [major browsers and Assistive Technologies](https://github.com/dequelabs/axe-core/blob/develop/doc/accessibility-supported.md#accessibility-supported)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Description of the changes

- Tackled the issue of CircleCI kicking the bucket intermittently due to timeout error on script execution for mobile web-driver (chrome-mobile).
- Github issue: https://github.com/dequelabs/axe-core/issues/805
- Although this looked like grunt concurrency, or non-availability of gecko-driver, or docker base image issue, this was purely a configuration for web-driver.
- Also over-rid node ENV to not default to Http2, to avoid experimental warning on the terminal.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
- Refer Circle CI for relevant commit to see logs (https://circleci.com/gh/dequelabs/axe-core/1164)

### CODE REVIEW

**Comment by WilcoFiers** [comment]
Lets run this a bunch of time to see if it solved the problem.

**Comment by jkodu** [comment]
re-ran build multiple times, succeeds on each run - https://circleci.com/gh/dequelabs/axe-core/tree/build-failure-fix

**Comment by jkodu** [comment]
@dylanb sure thing.

**Comment by dylanb** [comment]
@jkodu looks like this got merged already

**Comment by jkodu** [comment]
@dylanb 
Yup, we merge before this was raised, to help with reducing the number of re-builds we had to run. Will cater to the requested changes in the next issue I am tackling. In my radar.

**Pull request merged**
