### PR TITLE
chore: Update develop from master

### PR DESCRIPTION
**Pull request by WilcoFiers**
Couldn't do this directly because of some merge conflict.

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [x] Follows the commit message policy, appropriate for next version
- [x] Has documentation updated, a DU ticket, or requires no documentation change
- [x] Includes new tests, or was unnecessary
- [x] Code is reviewed for security by: Jey

### CODE REVIEW

**Comment by stephenmathieson** [comment]
We should put checks in place to avoid these PRs. Regardless, this LGTM!

**Comment by jkodu** [comment]
I had a similar issue when releasing `attest-ruby`. 
Think this was a sub-set issue due to migration from `bitbucket`.

**Comment by WilcoFiers** [comment]
Someone fill out the checks please.

**Comment by jkodu** [comment]
@WilcoFiers - Done

**Pull request merged**
