### PR TITLE
refactor: rename aria-input-field-label and aria-toggle-field-label

### PR DESCRIPTION
**Pull request by jkodu**
Renamed below rules & associated references:
- `aria-toggle-field-label` > `aria-toggle-field-name`
- `aria-input-field-label` > `aria-input-field-name`

Closes issue:
- https://github.com/dequelabs/axe-core/issues/1449#issuecomment-503545917

@straker - if and when this is merged this needs to become a part of 3.3 release.

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [x] Follows the commit message policy, appropriate for next version
- [x] Has documentation updated, a DU ticket, or requires no documentation change
- [x] Includes new tests, or was unnecessary
- [x] Code is reviewed for security by: Steve

### CODE REVIEW

**Comment by straker** [comment]
Is renaming a rule considered a breaking change? If custom configs were to disable it it would not longer work

**Comment by jkodu** [comment]
@straker these rules have not made it to a release yet. They were merged only 20 days ago.
- https://github.com/dequelabs/axe-core/pull/1450
- https://github.com/dequelabs/axe-core/pull/1610

So I do not think they would be considered a breaking change.

**Comment by straker** [comment]
@jkodu Unfortunately they are part of the 3.3 release so we can't rename them now :(

**Comment by jkodu** [comment]
@straker given @WilcoFiers has agreed for this change to be in 3.3, I will leave it with you to do the necessary cherry picking into 3.3 release.

**Pull request merged**
