### PR TITLE
feat(rule): add ACT Rule IDs to test rule objects

### PR DESCRIPTION
**Pull request by rweberkaf**
Add new property `actIds` to axe-core rule objects and populate with ACT Rule IDs; update validation schema to permit them. Link to corresponding ACT description pages in `rule-descriptions.md`.

Closes issue: #2820

### CODE REVIEW

**Comment by straker** [comment]
Thank you for the pr. @WilcoFiers will need to look over it, but we've been super busy preparing for the 4.2 release coming in the new few weeks. I'm not sure this pr will get in before the release so it might be a bit before he can get to it.

**Comment by WilcoFiers** [comment]
@rweberkaf Just to update you on this. This PR in came in just a little too late to make it into the 4.2 release. We'll pull this in after 4.2 is released. Some time next week I imagine.

**Review by WilcoFiers — APPROVED** [review]

**Comment by WilcoFiers** [comment]
@rweberkaf can you merge develop back into your branch. To resolve the merge conflict, best to just rerun `grunt build`. It'll create a new version of the file that's conflicting now.

**Comment by rweberkaf** [comment]
All set, @WilcoFiers , thank you!

**Comment by WilcoFiers** [comment]
Thank you for the contribution @rweberkaf! It is very much appreciated.

**Comment by WilcoFiers** [comment]
And for the record, I reviewed this PR for security.

**Review by WilcoFiers — APPROVED** [review]

**Pull request merged**
