### PR TITLE
fix: add section508 tags to rules

### PR DESCRIPTION
**Pull request by marcysutton**
This does not extend to best practice rules. Closes https://github.com/dequelabs/axe-core/issues/578

### CODE REVIEW

**Comment by iamrafan** [comment]
Should we also make the tags consistent for the following rules:

Rule ID | Rule-descriptions list | Individual rule page
-- | -- | --
table-fake-caption | section508.22.g | 1194.22 (g),   1194.22 (h)
td-has-header | section508.22.g | 1194.22 (g),   1194.22 (h)
td-headers-attr | section508.22.g | 1194.22 (g),   1194.22 (h)
th-has-data-cells | section508.22.g | 1194.22 (g),   1194.22 (h)

**Comment by marcysutton** [comment]
On second thought, we'll have to evaluate these tags to see if they're appropriate, or if the help pages should change instead. I'll talk with the team and circle back to it now that we have a PR open.

**Comment by iamrafan** [comment]
@marcysutton sure, thanks

**Comment by marcysutton** [comment]
@isner do you know if axe-core has the source of truth, or DQU? I assumed it was the former, which means we need to update the help pages instead and this PR can be closed.

**Comment by marcysutton** [comment]
Confirmed: these updates need to happen on DQU, so I'm going to close this PR. Stay tuned!

**Pull request closed without merging**
