### PR TITLE
chore: Convert ALL tabs to spaces

### PR DESCRIPTION
**Pull request by WilcoFiers**
Missed a couple of 'm.

### CODE REVIEW

**Review by stephenmathieson — COMMENTED** [review]
Could add a `.json` extension to these files so that Prettier would do its thing 🤷‍♂️

**Comment by WilcoFiers** [comment]
Wouldn't  the `*.{json,md,js}` do that @stephenmathieson?

**Comment by stephenmathieson** [comment]
> Wouldn't the *.{json,md,js} do that @stephenmathieson?

No, the files start with `.`, so that glob won't match.

**Comment by stephenmathieson** [comment]
First, do this:

```
git mv .huskyrc .huskyrc.json
git mv .prettierrc .prettierrc.json
```

Then update `package.json#scripts` to include:

```
"fmt": "prettier --write .*.json *.{json,md,js} ......."
```

The first glob (`.*.json`) will cover the `git mv`ed config files.

**Review by stephenmathieson — APPROVED** [review]

**Pull request merged**
